import os
from dotenv import load_dotenv

load_dotenv()

KAFKA_FASTAPI_PRODUCER_CLIENT_ID=os.getenv('KAFKA_FASTAPI_PRODUCER_CLIENT_ID')
KAFKA_BROKER_URL=os.getenv('KAFKA_BROKER_URL')

TEXTRACT_ACCESS_KEY=os.getenv('TEXTRACT_ACCESS_KEY')
TEXTRACT_SECRET_ACCESS_KEY=os.getenv('TEXTRACT_SECRET_ACCESS_KEY')
TEXTRACT_BUCKET_NAME=os.getenv('TEXTRACT_BUCKET_NAME')
TEXTRACT_BUCKET_REGION=os.getenv('TEXTRACT_BUCKET_REGION')

DATABASE_URL=os.getenv('DATABASE_URL')

CHUNK_WORKER_TOPIC = os.getenv('CHUNK_WORKER_TOPIC')
EMBEDDING_PROVIDER= os.getenv('EMBEDDING_PROVIDER')