"""add chunk_completed flag

Revision ID: 3f9252c83b2c
Revises: b6f8c830046a
Create Date: 2026-01-31 16:07:05.507378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9252c83b2c'
down_revision: Union[str, Sequence[str], None] = 'b6f8c830046a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # 1️⃣ Add column with safe default
    op.add_column(
        'documents',
        sa.Column(
            'chunk_completed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunk_completed')
    # ### end Alembic commands ###
