"""add new flag and status fields to document model

Revision ID: 5f0cf6e665c8
Revises: 74ad00e97d76
Create Date: 2026-01-26 20:36:04.839763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0cf6e665c8'
down_revision: Union[str, Sequence[str], None] = '74ad00e97d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_completed', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('embedding_completed', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.Enum('UPLOADED', 'OCR_IN_PROGRESS', 'OCR_DONE', 'EMBEDDING_IN_PROGRESS', 'EMBEDDING_DONE', 'OCR_FAILED', 'EMBEDDING_FAILED', name='processingstatus', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'embedding_completed')
    op.drop_column('documents', 'ocr_completed')
    # ### end Alembic commands ###
