"""remove id from pure association table of collection and document

Revision ID: 726fcf553346
Revises: 7f219d26c0e2
Create Date: 2026-01-23 11:41:04.926988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726fcf553346'
down_revision: Union[str, Sequence[str], None] = '7f219d26c0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_documents_uuid'), table_name='collection_documents')
    op.drop_column('collection_documents', 'uuid')
    op.drop_column('collection_documents', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_documents', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('collection_documents', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_collection_documents_uuid'), 'collection_documents', ['uuid'], unique=True)
    # ### end Alembic commands ###
