"""add ai json metadata field

Revision ID: 7f6009fd3a19
Revises: 726fcf553346
Create Date: 2026-01-23 17:08:36.079494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f6009fd3a19'
down_revision: Union[str, Sequence[str], None] = '726fcf553346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('documents', 'document_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'document_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'ai_metadata')
    # ### end Alembic commands ###
