import os
from dotenv import load_dotenv

load_dotenv()

TEXTRACT_ACCESS_KEY=os.getenv('TEXTRACT_ACCESS_KEY')
TEXTRACT_SECRET_ACCESS_KEY=os.getenv('TEXTRACT_SECRET_ACCESS_KEY')
TEXTRACT_BUCKET_NAME=os.getenv('TEXTRACT_BUCKET_NAME')
TEXTRACT_BUCKET_REGION=os.getenv('TEXTRACT_BUCKET_REGION')

DATABASE_URL=os.getenv('DATABASE_URL')